# Generated by Django 4.0.2 on 2022-02-24 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_id',
            field=models.UUIDField(default=uuid.UUID('9dd161c6-0919-48e4-bdde-24245c5a01d5'), unique=True),
        ),
    ]
