# Generated by Django 4.0.2 on 2022-02-06 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='topic',
            field=models.CharField(default=datetime.datetime(2022, 2, 6, 7, 28, 13, 781407, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
